chore: simplify CI workflow, add coverage job

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1,9 +1,8 @@
-# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
-# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
-
-name: Node.js CI
+name: '@ngworker/lumberjack CI'
 
 env:
+  ANGULAR_LATEST: 11.1.x
+  NODE_LATEST: 12.x
   NODE_OPTIONS: --max_old_space_size=4096
 
 on:
@@ -16,17 +15,12 @@ jobs:
   lint:
     runs-on: ubuntu-latest
 
-    strategy:
-      matrix:
-        node-version: [12.x]
-        angular-version: [11.1.x]
-
     steps:
       - uses: actions/checkout@v2
-      - name: Use Node.js ${{ matrix.node-version }}
+      - name: Use Node.js ${{ env.NODE_LATEST }}
         uses: actions/setup-node@v2
         with:
-          node-version: ${{ matrix.node-version }}
+          node-version: ${{ env.NODE_LATEST }}
 
       - name: Variable-Yarn cache directory path
         id: yarn-cache-dir-path
@@ -35,30 +29,22 @@ jobs:
         uses: actions/cache@v2
         with:
           path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
-          key: ${{ runner.os }}-node-${{ matrix.node-version }}-angular-${{ matrix.angular-version }}-yarn-${{ hashFiles('**/yarn.lock') }}
+          key: ${{ runner.os }}-node-${{ env.NODE_LATEST }}-angular-${{ env.ANGULAR_LATEST }}-yarn-${{ hashFiles('yarn.lock') }}
           restore-keys: |
-            ${{ runner.os }}-node-${{ matrix.node-version }}-angular-${{ matrix.angular-version }}-yarn-
+            ${{ runner.os }}-node-${{ env.NODE_LATEST }}-angular-${{ env.ANGULAR_LATEST }}-yarn-
+            ${{ runner.os }}-node-${{ env.NODE_LATEST }}-angular-
       - run: yarn install
       - run: yarn lint
 
   build:
     runs-on: ubuntu-latest
 
-    strategy:
-      matrix:
-        node-version: [12.x]
-        angular-version: [11.1.x]
-
     steps:
       - uses: actions/checkout@v2
-      - name: Use Node.js ${{ matrix.node-version }}
+      - name: Use Node.js ${{ env.NODE_LATEST }}
         uses: actions/setup-node@v2
         with:
-          node-version: ${{ matrix.node-version }}
-      - name: Use Angular version ${{ matrix.angular-version }}
-        uses: ngworker/angular-versions-action@v2
-        with:
-          angular_version: ${{ matrix.angular-version }}
+          node-version: ${{ env.NODE_LATEST }}
 
       - name: Variable-Yarn cache directory path
         id: yarn-cache-dir-path
@@ -67,9 +53,10 @@ jobs:
         uses: actions/cache@v2
         with:
           path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
-          key: ${{ runner.os }}-node-${{ matrix.node-version }}-angular-${{ matrix.angular-version }}-yarn-${{ hashFiles('**/yarn.lock') }}
+          key: ${{ runner.os }}-node-${{ env.NODE_LATEST }}-angular-${{ env.ANGULAR_LATEST }}-yarn-${{ hashFiles('yarn.lock') }}
           restore-keys: |
-            ${{ runner.os }}-node-${{ matrix.node-version }}-angular-${{ matrix.angular-version }}-yarn-
+            ${{ runner.os }}-node-${{ env.NODE_LATEST }}-angular-${{ env.ANGULAR_LATEST }}-yarn-
+            ${{ runner.os }}-node-${{ env.NODE_LATEST }}-angular-
       - run: yarn install
       - run: yarn build:lib
       - uses: actions/upload-artifact@v2
@@ -83,15 +70,17 @@ jobs:
 
     strategy:
       matrix:
-        node-version: [12.x]
         angular-version: [9.0.x, 9.1.x, 10.0.x, 10.1.x, 10.2.x, 11.0.x, 11.1.x]
+
+    env:
+      IS_ANGULAR_LATEST: ${{ matrix.angular-version == env.ANGULAR_LATEST }}
 
     steps:
       - uses: actions/checkout@v2
-      - name: Use Node.js ${{ matrix.node-version }}
+      - name: Use Node.js ${{ env.NODE_LATEST }}
         uses: actions/setup-node@v2
         with:
-          node-version: ${{ matrix.node-version }}
+          node-version: ${{ env.NODE_LATEST }}
       - name: Use Angular version ${{ matrix.angular-version }}
         uses: ngworker/angular-versions-action@v2
         with:
@@ -104,32 +93,13 @@ jobs:
         uses: actions/cache@v2
         with:
           path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
-          key: ${{ runner.os }}-node-${{ matrix.node-version }}-angular-${{ matrix.angular-version }}-yarn-${{ hashFiles('**/yarn.lock') }}
+          key: ${{ runner.os }}-node-${{ env.NODE_LATEST }}-angular-${{ matrix.angular-version }}-yarn-${{ hashFiles('yarn.lock') }}
           restore-keys: |
-            ${{ runner.os }}-node-${{ matrix.node-version }}-angular-${{ matrix.angular-version }}-yarn-
+            ${{ runner.os }}-node-${{ env.NODE_LATEST }}-angular-${{ matrix.angular-version }}-yarn-
+            ${{ runner.os }}-node-${{ env.NODE_LATEST }}-angular-
       - run: yarn install
       - run: yarn test:internal:ci
-
-      - if: matrix.angular-version == '11.1.x'
-        run: yarn test:lib:ci
-      - if: matrix.angular-version != '11.1.x'
-        run: yarn test:lib:ci --code-coverage=false
-      - if: matrix.angular-version == '11.1.x'
-        run: yarn merge-lcov-reports
-      - if: matrix.angular-version == '11.1.x'
-        uses: romeovs/lcov-reporter-action@v0.2.19
-        with:
-          github-token: ${{ secrets.GITHUB_TOKEN }}
-          lcov-file: coverage/lcov.info
-      - if: matrix.angular-version == '11.1.x'
-        name: Upload @ngworker/lumberjack coverage report
-        uses: actions/upload-artifact@v2
-        with:
-          name: lumberjack-coverage
-          path: |
-            coverage/libs/ngworker/lumberjack
-            !coverage/**/lcov.info
-          if-no-files-found: error
+      - run: yarn test:lib:ci
 
   app:
     runs-on: ubuntu-latest
@@ -158,9 +128,10 @@ jobs:
         uses: actions/cache@v2
         with:
           path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
-          key: ${{ runner.os }}-node-${{ matrix.node-version }}-angular-${{ matrix.angular-version }}-yarn-${{ hashFiles('**/yarn.lock') }}
+          key: ${{ runner.os }}-node-${{ matrix.node-version }}-angular-${{ matrix.angular-version }}-yarn-${{ hashFiles('yarn.lock') }}
           restore-keys: |
             ${{ runner.os }}-node-${{ matrix.node-version }}-angular-${{ matrix.angular-version }}-yarn-
+            ${{ runner.os }}-node-${{ matrix.node-version }}-angular-
       - run: yarn install
       - run: yarn delete-path-alias @ngworker/lumberjack
       - run: yarn delete-path-alias @ngworker/lumberjack/*-driver
@@ -170,27 +141,7 @@ jobs:
           path: node_modules/@ngworker/lumberjack
       - run: npx ngcc || true
 
-      - if: matrix.angular-version == '11.1.x'
-        run: yarn test:ci
-      - if: matrix.angular-version != '11.1.x'
-        run: yarn test:ci --code-coverage=false
-      - if: matrix.angular-version == '11.1.x'
-        run: yarn merge-lcov-reports
-      - if: matrix.angular-version == '11.1.x'
-        uses: romeovs/lcov-reporter-action@v0.2.19
-        with:
-          github-token: ${{ secrets.GITHUB_TOKEN }}
-          lcov-file: coverage/lcov.info
-      - if: matrix.angular-version == '11.1.x'
-        name: Upload lumberjack-app coverage report
-        uses: actions/upload-artifact@v2
-        with:
-          name: lumberjack-app-coverage
-          path: |
-            coverage/apps/lumberjack-app
-            !coverage/**/lcov.info
-          if-no-files-found: error
-
+      - run: yarn test:ci
       - run: yarn build
 
   e2e:
@@ -199,15 +150,14 @@ jobs:
 
     strategy:
       matrix:
-        node-version: [12.x]
         angular-version: [9.0.x, 9.1.x, 10.0.x, 10.1.x, 10.2.x, 11.0.x, 11.1.x]
 
     steps:
       - uses: actions/checkout@v2
-      - name: Use Node.js ${{ matrix.node-version }}
+      - name: Use Node.js ${{ env.NODE_LATEST }}
         uses: actions/setup-node@v2
         with:
-          node-version: ${{ matrix.node-version }}
+          node-version: ${{ env.NODE_LATEST }}
       - name: Use Angular version ${{ matrix.angular-version }}
         uses: ngworker/angular-versions-action@v2
         with:
@@ -220,9 +170,10 @@ jobs:
         uses: actions/cache@v2
         with:
           path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
-          key: ${{ runner.os }}-node-${{ matrix.node-version }}-angular-${{ matrix.angular-version }}-yarn-${{ hashFiles('**/yarn.lock') }}
+          key: ${{ runner.os }}-node-${{ env.NODE_LATEST }}-angular-${{ matrix.angular-version }}-yarn-${{ hashFiles('yarn.lock') }}
           restore-keys: |
-            ${{ runner.os }}-node-${{ matrix.node-version }}-angular-${{ matrix.angular-version }}-yarn-
+            ${{ runner.os }}-node-${{ env.NODE_LATEST }}-angular-${{ matrix.angular-version }}-yarn-
+            ${{ runner.os }}-node-${{ env.NODE_LATEST }}-angular-
       - run: yarn install
       - run: yarn delete-path-alias @ngworker/lumberjack
       - run: yarn delete-path-alias @ngworker/lumberjack/*-driver
@@ -238,3 +189,53 @@ jobs:
           sudo apt-get --only-upgrade install google-chrome-stable
           google-chrome --version
       - run: yarn e2e
+
+  coverage:
+    steps:
+      - uses: actions/checkout@v2
+      - name: Use Node.js ${{ env.NODE_LATEST }}
+        uses: actions/setup-node@v2
+        with:
+          node-version: ${{ env.NODE_LATEST }}
+
+      - name: Variable-Yarn cache directory path
+        id: yarn-cache-dir-path
+        run: echo "::set-output name=dir::$(yarn cache dir)"
+      - name: Cache Yarn cache directory
+        uses: actions/cache@v2
+        with:
+          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
+          key: ${{ runner.os }}-node-${{ env.NODE_LATEST }}-angular-${{ env.ANGULAR_LATEST }}-yarn-${{ hashFiles('yarn.lock') }}
+          restore-keys: |
+            ${{ runner.os }}-node-${{ env.NODE_LATEST }}-angular-${{ env.ANGULAR_LATEST }}-yarn-
+            ${{ runner.os }}-node-${{ env.NODE_LATEST }}-angular-
+      - run: yarn install
+      - run: npx ngcc || true
+
+      - run: yarn test:coverage #--no-fail-on-failing-test-suite
+      - name: Upload lumberjack-app coverage report
+        uses: actions/upload-artifact@v2
+        with:
+          name: lumberjack-app-coverage
+          path: |
+            coverage/apps/lumberjack-app
+            !coverage/**/lcov.info
+          if-no-files-found: error
+
+      - run: yarn test:lib:coverage #--no-fail-on-failing-test-suite
+      - name: Upload @ngworker/lumberjack coverage report
+        uses: actions/upload-artifact@v2
+        with:
+          name: lumberjack-coverage
+          path: |
+            coverage/libs/ngworker/lumberjack
+            !coverage/**/lcov.info
+          if-no-files-found: error
+
+      - name: Merge test coverage reports
+        run: yarn merge-lcov-reports
+      - name: Report test coverage in PR description
+        uses: romeovs/lcov-reporter-action@v0.2.19
+        with:
+          github-token: ${{ secrets.GITHUB_TOKEN }}
+          lcov-file: coverage/lcov.info
